package convertgen

import (
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strings"
)

func formatSource(src []byte) ([]byte, error) {
	return format.Source(src)
}

func render(cfg Config, enums []enumModel, msgs []msgModel) ([]byte, error) {
	impMap := map[string]string{
		cfg.ProtoGoImport: aliasFor(cfg.ProtoGoImport),
	}
	for _, pol := range cfg.Enums {
		impMap[pol.DomainImport] = aliasFor(pol.DomainImport)
	}
	for _, pol := range cfg.Messages {
		impMap[pol.DomainImport] = aliasFor(pol.DomainImport)
	}

	needFmt := len(enums) > 0 || len(msgs) > 0
	needJSON := false
	for _, m := range msgs {
		for _, o := range m.Oneofs {
			for _, c := range o.Cases {
				if c.Convert == "raw_json_ptr" {
					needJSON = true
				}
			}
		}
	}

	var imps []imp
	for path, alias := range impMap {
		imps = append(imps, imp{Alias: alias, Path: path})
	}
	sort.Slice(imps, func(i, j int) bool { return imps[i].Path < imps[j].Path })

	var b strings.Builder
	b.WriteString("// Code generated by convertgen. DO NOT EDIT.\n\n")
	b.WriteString("package " + cfg.OutPackage + "\n\n")
	b.WriteString("import (\n")
	if needJSON {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if needFmt {
		b.WriteString("\t\"fmt\"\n")
	}
	if needFmt || needJSON {
		b.WriteString("\n")
	}
	for _, im := range imps {
		fmt.Fprintf(&b, "\t%s %q\n", im.Alias, im.Path)
	}
	b.WriteString(")\n")

	for _, e := range enums {
		writeEnum(&b, e)
	}
	for _, m := range msgs {
		writeMessage(&b, m)
	}
	return []byte(b.String()), nil
}

func writeEnum(b *strings.Builder, e enumModel) {
	fmt.Fprintf(b, "\nfunc %sToProto(v %s) %s {\n", e.Name, e.DomainIdent, e.ProtoIdent)
	b.WriteString("\tswitch v {\n")
	for _, v := range e.Values {
		fmt.Fprintf(b, "\tcase %s:\n\t\treturn %s\n", v.DomainIdent, v.ProtoIdent)
	}
	b.WriteString("\tdefault:\n\t\treturn 0\n\t}\n}\n")

	fmt.Fprintf(b, "\nfunc %sFromProto(v %s) (%s, error) {\n", e.Name, e.ProtoIdent, e.DomainIdent)
	b.WriteString("\tswitch v {\n")
	for _, v := range e.Values {
		fmt.Fprintf(b, "\tcase %s:\n\t\treturn %s, nil\n", v.ProtoIdent, v.DomainIdent)
	}
	fmt.Fprintf(b, "\tdefault:\n\t\treturn %s, fmt.Errorf(%q, v)\n\t}\n}\n",
		e.ZeroDomain, e.Name+": unsupported proto value %v")
}

func writeMessage(b *strings.Builder, m msgModel) {
	if m.IsCompose {
		writeComposeToProto(b, m)
		writePointerSliceToProto(b, m)
		return
	}
	writeMessageToProto(b, m)
	if !m.ToProtoOnly {
		writeMessageFromProto(b, m)
	}
	writeMessageSlices(b, m)
}

func writeComposeToProto(b *strings.Builder, m msgModel) {
	fmt.Fprintf(b, "\nfunc %sToProto(in %s) *%s {\n", m.Name, m.DomainIdent, m.ProtoIdent)
	if m.Pointer {
		b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")
	}
	b.WriteString("\treturn &" + m.ProtoIdent + "{\n")
	for _, c := range m.Compose {
		arg := "in"
		if c.Getter != "" {
			arg = "in." + c.Getter + "()"
		}
		if c.Getter != "" {
			// repeated or nested collection from getter → FoosToProto
			fmt.Fprintf(b, "\t\t%s: %ssToProto(%s),\n", c.ProtoField, c.MessageFunc, arg)
		} else {
			fmt.Fprintf(b, "\t\t%s: %sToProto(%s),\n", c.ProtoField, c.MessageFunc, arg)
		}
	}
	b.WriteString("\t}\n}\n")
}

func writePointerSliceToProto(b *strings.Builder, m msgModel) {
	// Compose messages are typically singular aggregates; still emit ToProto slice helper.
	elem := m.DomainIdent
	fmt.Fprintf(b, "\nfunc %sToProto(in []%s) []*%s {\n", m.Plural, elem, m.ProtoIdent)
	fmt.Fprintf(b, "\tout := make([]*%s, 0, len(in))\n", m.ProtoIdent)
	b.WriteString("\tfor _, v := range in {\n")
	fmt.Fprintf(b, "\t\tout = append(out, %sToProto(v))\n", m.Name)
	b.WriteString("\t}\n\treturn out\n}\n")
}

func writeMessageToProto(b *strings.Builder, m msgModel) {
	fmt.Fprintf(b, "\nfunc %sToProto(in %s) *%s {\n", m.Name, m.DomainIdent, m.ProtoIdent)

	if m.HasOneofs && len(m.Fields) == 0 {
		b.WriteString("\tswitch {\n")
		for _, o := range m.Oneofs {
			of := snakeToCamel(o.Name)
			for _, c := range o.Cases {
				fmt.Fprintf(b, "\tcase in.%s != nil:\n", c.DomainField)
				fmt.Fprintf(b, "\t\treturn &%s{%s: &%s{", m.ProtoIdent, of, c.WrapperType)
				writeOneofWrapperValue(b, c, "in."+c.DomainField)
				b.WriteString("}}\n")
			}
		}
		b.WriteString("\tdefault:\n\t\treturn nil\n\t}\n}\n")
		return
	}

	if m.Pointer {
		b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")
	}

	b.WriteString("\tout := &" + m.ProtoIdent + "{}\n")
	for _, f := range m.Fields {
		writeFieldToProtoAssign(b, f)
	}
	if m.HasOneofs {
		b.WriteString("\tswitch {\n")
		for _, o := range m.Oneofs {
			of := snakeToCamel(o.Name)
			for _, c := range o.Cases {
				fmt.Fprintf(b, "\tcase in.%s != nil:\n", c.DomainField)
				fmt.Fprintf(b, "\t\tout.%s = &%s{", of, c.WrapperType)
				writeOneofWrapperValue(b, c, "in."+c.DomainField)
				b.WriteString("}\n")
			}
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn out\n}\n")
}

func domainExpr(f fieldModel) string {
	if f.Getter != "" {
		return "in." + f.Getter + "()"
	}
	return "in." + f.DomainField
}

func writeFieldToProtoAssign(b *strings.Builder, f fieldModel) {
	src := domainExpr(f)
	switch f.Convert {
	case "error_string":
		fmt.Fprintf(b, "\tif err := %s; err != nil {\n", src)
		fmt.Fprintf(b, "\t\tout.%s = err.Error()\n", f.ProtoField)
		b.WriteString("\t}\n")
		return
	case "uuid_string":
		fmt.Fprintf(b, "\tout.%s = %s.String()\n", f.ProtoField, src)
		return
	case "bytes_copy":
		fmt.Fprintf(b, "\tout.%s = append([]byte(nil), %s...)\n", f.ProtoField, src)
		return
	}

	switch {
	case f.IsRepeated && f.Kind == kindMessage:
		fmt.Fprintf(b, "\tout.%s = %ssToProto(%s)\n", f.ProtoField, f.MessageFunc, src)
	case f.IsRepeated:
		fmt.Fprintf(b, "\tout.%s = append([]string(nil), %s...)\n", f.ProtoField, src)
	case f.Kind == kindEnum:
		fmt.Fprintf(b, "\tout.%s = %sToProto(%s)\n", f.ProtoField, f.EnumFunc, src)
	case f.Kind == kindMessage:
		fmt.Fprintf(b, "\tout.%s = %sToProto(%s)\n", f.ProtoField, f.MessageFunc, src)
	case f.Kind == kindBytes:
		fmt.Fprintf(b, "\tout.%s = append([]byte(nil), %s...)\n", f.ProtoField, src)
	default:
		fmt.Fprintf(b, "\tout.%s = %s\n", f.ProtoField, src)
	}
}

func writeOneofWrapperValue(b *strings.Builder, c oneofCaseModel, domainExpr string) {
	switch {
	case c.Convert == "raw_json_ptr":
		fmt.Fprintf(b, "%s: append([]byte(nil), (*%s)...)", c.WrapperField, domainExpr)
	case c.Kind == kindMessage:
		fmt.Fprintf(b, "%s: %sToProto(*%s)", c.WrapperField, c.MessageFunc, domainExpr)
	default:
		fmt.Fprintf(b, "%s: *%s", c.WrapperField, domainExpr)
	}
}

func writeMessageFromProto(b *strings.Builder, m msgModel) {
	fmt.Fprintf(b, "\nfunc %sFromProto(in *%s) (%s, error) {\n", m.Name, m.ProtoIdent, m.DomainIdent)
	if m.Pointer {
		b.WriteString("\tif in == nil {\n")
		fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(%q)\n", m.Name+": nil")
		b.WriteString("\t}\n")
		fmt.Fprintf(b, "\tout := &%s{}\n", m.DomainBase)
	} else {
		b.WriteString("\tvar out " + m.DomainIdent + "\n")
		b.WriteString("\tif in == nil {\n")
		fmt.Fprintf(b, "\t\treturn out, fmt.Errorf(%q)\n", m.Name+": nil")
		b.WriteString("\t}\n")
	}

	for _, f := range m.Fields {
		if f.DomainField == "" {
			continue // getter-only; should not happen without to_proto_only
		}
		writeFieldFromProto(b, f)
	}

	for _, o := range m.Oneofs {
		fmt.Fprintf(b, "\tswitch o := in.%s().(type) {\n", o.Getter)
		for _, c := range o.Cases {
			fmt.Fprintf(b, "\tcase *%s:\n", c.WrapperType)
			writeOneofFromProtoCase(b, c)
		}
		fmt.Fprintf(b, "\tdefault:\n\t\treturn out, fmt.Errorf(%q)\n", m.Name+": "+o.Name+" is required")
		b.WriteString("\t}\n")
	}

	b.WriteString("\treturn out, nil\n}\n")
}

func writeFieldFromProto(b *strings.Builder, f fieldModel) {
	switch {
	case f.IsRepeated && f.Kind == kindMessage:
		fmt.Fprintf(b, "\t{\n\t\tv, err := %ssFromProto(in.%s)\n", f.MessageFunc, f.ProtoField)
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = v\n\t}\n", f.DomainField)
	case f.IsRepeated:
		fmt.Fprintf(b, "\tout.%s = append([]string(nil), in.%s...)\n", f.DomainField, f.ProtoField)
	case f.Kind == kindEnum:
		fmt.Fprintf(b, "\t{\n\t\tv, err := %sFromProto(in.%s)\n", f.EnumFunc, f.ProtoField)
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = v\n\t}\n", f.DomainField)
	case f.Kind == kindMessage:
		fmt.Fprintf(b, "\t{\n\t\tv, err := %sFromProto(in.%s)\n", f.MessageFunc, f.ProtoField)
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = v\n\t}\n", f.DomainField)
	case f.Kind == kindBytes || f.Convert == "bytes_copy":
		fmt.Fprintf(b, "\tout.%s = append([]byte(nil), in.%s...)\n", f.DomainField, f.ProtoField)
	default:
		fmt.Fprintf(b, "\tout.%s = in.%s\n", f.DomainField, f.ProtoField)
	}
}

func writeOneofFromProtoCase(b *strings.Builder, c oneofCaseModel) {
	switch {
	case c.Convert == "raw_json_ptr":
		fmt.Fprintf(b, "\t\traw := json.RawMessage(append([]byte(nil), o.%s...))\n", c.WrapperField)
		fmt.Fprintf(b, "\t\tout.%s = &raw\n", c.DomainField)
	case c.Kind == kindMessage:
		fmt.Fprintf(b, "\t\tv, err := %sFromProto(o.%s)\n", c.MessageFunc, c.WrapperField)
		b.WriteString("\t\tif err != nil {\n\t\t\treturn out, err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tout.%s = &v\n", c.DomainField)
	default:
		fmt.Fprintf(b, "\t\tv := o.%s\n", c.WrapperField)
		fmt.Fprintf(b, "\t\tout.%s = &v\n", c.DomainField)
	}
}

func writeMessageSlices(b *strings.Builder, m msgModel) {
	elem := m.DomainIdent
	fmt.Fprintf(b, "\nfunc %sToProto(in []%s) []*%s {\n", m.Plural, elem, m.ProtoIdent)
	fmt.Fprintf(b, "\tout := make([]*%s, 0, len(in))\n", m.ProtoIdent)
	b.WriteString("\tfor _, v := range in {\n")
	fmt.Fprintf(b, "\t\tout = append(out, %sToProto(v))\n", m.Name)
	b.WriteString("\t}\n\treturn out\n}\n")

	if m.ToProtoOnly {
		return
	}

	fmt.Fprintf(b, "\nfunc %sFromProto(in []*%s) ([]%s, error) {\n", m.Plural, m.ProtoIdent, elem)
	fmt.Fprintf(b, "\tout := make([]%s, 0, len(in))\n", elem)
	b.WriteString("\tfor _, v := range in {\n")
	b.WriteString("\t\tif v == nil {\n\t\t\tcontinue\n\t\t}\n")
	fmt.Fprintf(b, "\t\tconverted, err := %sFromProto(v)\n", m.Name)
	b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	b.WriteString("\t\tout = append(out, converted)\n")
	b.WriteString("\t}\n\treturn out, nil\n}\n")
}

func aliasFor(path string) string {
	switch {
	case strings.HasSuffix(path, "/engine"):
		return "engine"
	case strings.HasSuffix(path, "/args"):
		return "args"
	case strings.HasSuffix(path, "/db"):
		return "db"
	case strings.HasSuffix(path, "/workflows/v1"):
		return "workflowv1"
	default:
		base := filepath.Base(path)
		if base == "v1" || base == "v2" {
			parent := filepath.Base(filepath.Dir(path))
			return parent + base
		}
		return base
	}
}

func zeroValue(domainImport, domainType string) string {
	if strings.HasSuffix(domainImport, "/engine") || strings.HasSuffix(domainImport, "/db") {
		return `""`
	}
	return fmt.Sprintf("%s.%s{}", aliasFor(domainImport), domainType)
}

func snakeToCamel(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func sortedKeys[T any](m map[string]T) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
