// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: convertgen/options/v1/options.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_convertgen_options_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         75000,
		Name:          "convertgen.options.v1.skip",
		Tag:           "varint,75000,opt,name=skip",
		Filename:      "convertgen/options/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         75001,
		Name:          "convertgen.options.v1.go_name",
		Tag:           "bytes,75001,opt,name=go_name",
		Filename:      "convertgen/options/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         75010,
		Name:          "convertgen.options.v1.domain_type",
		Tag:           "bytes,75010,opt,name=domain_type",
		Filename:      "convertgen/options/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool skip = 75000;
	E_Skip = &file_convertgen_options_v1_options_proto_extTypes[0]
	// optional string go_name = 75001;
	E_GoName = &file_convertgen_options_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string domain_type = 75010;
	E_DomainType = &file_convertgen_options_v1_options_proto_extTypes[2]
)

var File_convertgen_options_v1_options_proto protoreflect.FileDescriptor

const file_convertgen_options_v1_options_proto_rawDesc = "" +
	"\n" +
	"#convertgen/options/v1/options.proto\x12\x15convertgen.options.v1\x1a google/protobuf/descriptor.proto:3\n" +
	"\x04skip\x12\x1d.google.protobuf.FieldOptions\x18\xf8\xc9\x04 \x01(\bR\x04skip:8\n" +
	"\ago_name\x12\x1d.google.protobuf.FieldOptions\x18\xf9\xc9\x04 \x01(\tR\x06goName:B\n" +
	"\vdomain_type\x12\x1f.google.protobuf.MessageOptions\x18\x82\xca\x04 \x01(\tR\n" +
	"domainTypeB8Z6github.com/cogitatorum/convertgen/options/v1;optionsv1b\x06proto3"

var file_convertgen_options_v1_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_convertgen_options_v1_options_proto_depIdxs = []int32{
	0, // 0: convertgen.options.v1.skip:extendee -> google.protobuf.FieldOptions
	0, // 1: convertgen.options.v1.go_name:extendee -> google.protobuf.FieldOptions
	1, // 2: convertgen.options.v1.domain_type:extendee -> google.protobuf.MessageOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_convertgen_options_v1_options_proto_init() }
func file_convertgen_options_v1_options_proto_init() {
	if File_convertgen_options_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_convertgen_options_v1_options_proto_rawDesc), len(file_convertgen_options_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_convertgen_options_v1_options_proto_goTypes,
		DependencyIndexes: file_convertgen_options_v1_options_proto_depIdxs,
		ExtensionInfos:    file_convertgen_options_v1_options_proto_extTypes,
	}.Build()
	File_convertgen_options_v1_options_proto = out.File
	file_convertgen_options_v1_options_proto_goTypes = nil
	file_convertgen_options_v1_options_proto_depIdxs = nil
}
